# Generated by Django 2.1.3 on 2018-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='sawyer', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='isTop',
            field=models.BooleanField(default=False),
        ),
    ]
