# Generated by Django 2.1.3 on 2018-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
