# Generated by Django 2.1.3 on 2018-11-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rec', '0002_filesmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesmodel',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'pizza'},
        ),
    ]
