# Generated by Django 2.1.3 on 2018-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rec', '0005_auto_20181104_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='headImg')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.DeleteModel(
            name='FilesModel',
        ),
    ]
