# Generated by Django 2.1.3 on 2018-11-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rec', '0007_userphoto_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='userid',
        ),
    ]
