# Generated by Django 2.1.3 on 2018-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rec', '0009_userphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='file',
            field=models.FileField(default='thisisusersfile', upload_to='headImg'),
        ),
    ]
