# Generated by Django 2.1.3 on 2018-11-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rec', '0011_auto_20181105_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='file',
        ),
        migrations.AddField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(default='thisisusersphoto', upload_to='usersPhoto'),
        ),
    ]
